const samplejobsData = {
  data: [
    {
      job_id: "pNendH4INIxsz3cpAAAAAA==",
      employer_name: "Zemoso Technologies",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsLVCnetf7W6_KFZAJ8isdTfAQYEepclfFbQYC&s=0",
      employer_website: null,
      employer_company_type: null,
      employer_linkedin: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Node Js Developer",
      job_apply_link:
        "https://in.linkedin.com/jobs/view/node-js-developer-at-zemoso-technologies-4070975170?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6408,
      apply_options: null,
      job_description:
        "About us: Zemoso Technologies is a Software Product Market Fit Studio that brings silicon valley style rapid prototyping and rapid application builds to Entrepreneurs and Corporate innovation. We offer Innovation as a service and work on ideas from scratch and take it to the Product Market Fit stage using Design Thinking->Lean Execution->Agile Methodology. We were featured as one of Deloitte Fastest 50 growing tech companies from India thrice (2016, 2018 and 2019). We were also featured in Deloitte Technology Fast 500 Asia Pacific both in 2016 and 2018. We are located in Hyderabad, India, and Dallas, US. We have recently incorporated another office in Waterloo, Canada. Our founders have had past successes - founded a decision management company acquired by SAP AG (now part of Hana Big data stack & NetWeaver BPM), early engineering team of Zoho (leading billion $ SaaS player) & some Private Equity experience. Marquee customers along with some exciting start-ups are part of our clientele. What You will do ● Create beautiful software experiences for our clients using design thinking, lean and agile methodology. ● Work on software products designed from scratch using the latest cutting edge technologies, platforms and languages such as NodeJs,Javascript.. ● Work in a dynamic, collaborative, transparent, non-hierarchical culture. ● Work in collaborative, fast-paced and value-driven teams to build innovative customer experiences for our clients. ● Help to grow the next generation of developers and have a positive impact on the industry. Basic Qualifications ● Experience: 3+ years. ● Hands-on development experience with a broad mix of languages such as NodeJS, Javascript etc. ● Server-side development experience mainly in and nodeJS can be considerable ● UI development experience in ReactJS or AngularJS or PolymerJS or EmberJS or Jquery etc. are good to have. ● Passion for software engineering and follow the best coding concepts.● Good to great problem solving and communication skills. Nice to have Qualifications ● Product and customer-centric mindset. ● Great OO skills, including design patterns. ● Experience with devops, continuous integration & deployment. ● Exposure to big data technologies, Machine Learning and NLP will be a plus",
      job_is_remote: false,
      job_posted_at_timestamp: 1731230760,
      job_posted_at_datetime_utc: "2024-11-10T09:26:00.000Z",
      job_city: "Mumbai",
      job_state: "MH",
      job_country: "IN",
      job_latitude: 19.075983,
      job_longitude: 72.877655,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=node.js+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DpNendH4INIxsz3cpAAAAAA%3D%3D&vssid=jobs-detail-viewer",
      job_offer_expiration_datetime_utc: "2024-12-10T09:26:00.000Z",
      job_offer_expiration_timestamp: 1733822760,
      job_required_experience: null,
      job_required_skills: null,
      job_required_education: null,
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: null,
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
      job_occupational_categories: null,
      job_naics_code: null,
      job_naics_name: null,
    },

    {
      job_id: "eIHY4TAmRx-msB0pAAAAAA==",
      employer_name: "GAMMASTACK",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe9SrAHrlx3HdfIEjZ_uVYc2e17OTMfAcMoauc&s=0",
      employer_website: "http://www.gammastack.com",
      employer_company_type: null,
      employer_linkedin: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Node.js Developer - Javascript/Express.js",
      job_apply_link:
        "https://in.linkedin.com/jobs/view/node-js-developer-javascript-express-js-at-gammastack-4071817161?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6339,
      apply_options: null,
      job_description:
        "Responsibilities • Lead the design, development, and implementation of complex Node.js applications • Architect scalable, performant, and maintainable server-side systems • Collaborate with cross-functional teams to define, design, and ship new features • Mentor and coach junior developers to improve their skills and productivity • Perform code reviews to ensure code quality and adherence to best practices • Stay up-to-date with the latest trends and technologies in Node.js development Requirements • Minimum of 3 years of experience in Node.js development • Proven track record of leading and delivering large-scale Node.js projects • Strong proficiency in JavaScript, with a good understanding of server-side templating languages • Experience with modern frameworks and libraries such as Express.js, Hapi.js, or Koa.js • Familiarity with database technologies such as PostgreSQL (MongoDB / MySQL is good to have) • Excellent communication and leadership skills • Ability to work effectively in a fast-paced, dynamic environment. (ref:hirist.tech)",
      job_is_remote: false,
      job_posted_at_timestamp: 1731025271,
      job_posted_at_datetime_utc: "2024-11-08T00:21:11.000Z",
      job_city: "इन्दौर",
      job_state: "MP",
      job_country: "IN",
      job_latitude: 22.719568,
      job_longitude: 75.85773,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=node.js+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DeIHY4TAmRx-msB0pAAAAAA%3D%3D&vssid=jobs-detail-viewer",
      job_offer_expiration_datetime_utc: "2024-12-08T00:21:10.000Z",
      job_offer_expiration_timestamp: 1733617270,
      job_required_experience: null,
      job_required_skills: null,
      job_required_education: null,
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: null,
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
      job_occupational_categories: null,
      job_naics_code: null,
      job_naics_name: null,
    },
    {
      job_id: "BJeMmO2gHDSf6yV6AAAAAA==",
      employer_name: "Ace Technosys",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQst3dq3V-HOHmymsCrXsTfgInMkkGwbJ5TXvmP&s=0",
      employer_website: null,
      employer_company_type: null,
      employer_linkedin: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Node.js Developer",
      job_apply_link:
        "https://in.linkedin.com/jobs/view/node-js-developer-at-ace-technosys-4066697018?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6404,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://in.linkedin.com/jobs/view/node-js-developer-at-ace-technosys-4066697018?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
          is_direct: false,
        },
        {
          publisher: "Jobrapido.com",
          apply_link:
            "https://in.jobrapido.com/jobpreview/3544702797914046464?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
          is_direct: false,
        },
      ],
      job_description:
        "Skills: JavaScript, Asynchronous programming, Node Package Manager (npm), Express.js, RESTful APIs, MongoDB, Debugging, Event-driven programming. Company Overview: Ace Technosys is a leading IT service company headquartered in Mumbai with a team of 201-500 employees. Specializing in a wide range of technological services, Ace Technosys aims to deliver innovative solutions to clients. Our website is www.acetechnosys.com. Job Overview: Ace Technosys is seeking a skilled Node.js Developer for a mid-level position. This role requires candidates with 4 to 6 years of work experience. Available job locations include Ghatkopar, Andheri, Kalyan, Golaghat, Patna, and Guwahati. We offer flexible employment types including full-time, part-time, remote, freelance, hybrid, contract, and contract-to-hire positions. Qualifications And Skills: • Proficiency in JavaScript (Mandatory skill) • Experience with Node Package Manager (npm) (Mandatory skill) • Familiarity with MongoDB (Mandatory skill) • Strong knowledge of asynchronous programming including promises and async/await patterns • Hands-on experience with Express.js for server-side development • Ability to create and maintain RESTful APIs • Sound debugging skills to troubleshoot application issues effectively • Understanding of event-driven programming in Node.js. Roles And Responsibilities: • Develop and maintain server-side applications using Node.js • Collaborate with front-end developers to integrate user-facing elements with server-side logic • Write reusable, testable, and efficient code • Design and implement low-latency, high-availability, and performance applications • Implement security and data protection measures • Participate in code reviews to ensure code quality and distribute knowledge • Troubleshoot and debug application issues, ensuring optimal performance and quality • Ensure that applications adhere to best practices and operational standards.",
      job_is_remote: false,
      job_posted_at_timestamp: 1730937600,
      job_posted_at_datetime_utc: "2024-11-07T00:00:00.000Z",
      job_city: "Golaghat",
      job_state: "AS",
      job_country: "IN",
      job_latitude: 26.523851,
      job_longitude: 93.96233,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=node.js+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DBJeMmO2gHDSf6yV6AAAAAA%3D%3D&vssid=jobs-detail-viewer",
      job_offer_expiration_datetime_utc: "2024-12-07T03:26:52.000Z",
      job_offer_expiration_timestamp: 1733542012,
      job_required_experience: {
        no_experience_required: "false",
        required_experience_in_months: "48",
        experience_mentioned: "true",
        experience_preferred: "false",
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: "false",
        professional_certification: "false",
        high_school: "false",
        associates_degree: "false",
        bachelors_degree: "true",
        degree_mentioned: "false",
        degree_preferred: "false",
        professional_certification_mentioned: "false",
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: null,
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
      job_occupational_categories: null,
      job_naics_code: null,
      job_naics_name: null,
    },
    {
      job_id: "FrMQocxlaVCHpKB_AAAAAA==",
      employer_name: "StackandCo",
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      employer_linkedin: null,
      job_publisher: "ZipRecruiter",
      job_employment_type: "FULLTIME",
      job_title: "Junior Developer (React and Node)",
      job_apply_link:
        "https://www.ziprecruiter.com/c/StackandCo/Job/Junior-Developer-(React-and-Node)/-in-Dublin,GA?jid=639257b77c23c790&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6798,
      apply_options: [
        {
          publisher: "ZipRecruiter",
          apply_link:
            "https://www.ziprecruiter.com/c/StackandCo/Job/Junior-Developer-(React-and-Node)/-in-Dublin,GA?jid=639257b77c23c790&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
          is_direct: false,
        },
      ],
      job_description:
        "Our client, a digital consultancy based in South Dublin, is looking for a talented Software Developer with a genuine passion for developing, as well as having a dedicated, committed work ethic to adopt new technologies and learn new skills. This is a unique opportunity for an intelligent, driven full stack developer to learn from an elite team of high calibre developers, who are making a massive impact in their industry. You will be working alongside the current team of developers. The key technologies currently used within the company are JavaScript, HTML5, CSS3, React and Node.js. Beneficial Skills Include • 2+ years' experience with Node and JavaScript • Experience with AWS • Experience with Frontend frameworks including React (preferred) or Angular or Vue • Knowledge of secure programming • DevOps experience highly beneficial As long as you are well experienced in software development and can demonstrate a capacity to adjust to using these modern technologies, send in your application. If this is the case, a portfolio of personal projects or a live github, stackoverflow account or other online material showcasing your ability would be advantageous.",
      job_is_remote: true,
      job_posted_at_timestamp: 1731178800,
      job_posted_at_datetime_utc: "2024-11-09T19:00:00.000Z",
      job_city: "Dublin",
      job_state: "GA",
      job_country: "US",
      job_latitude: 32.540443,
      job_longitude: -82.903755,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=node.js+developer+in+new-york,+usa&start=0&ltype=1&chips=date_posted:3days,employment_type:FULLTIME,requirements:years3under&schips=date_posted;3days,employment_type;FULLTIME,requirements;years3under&lrad=498&udm=8#vhid=vt%3D20/docid%3DFrMQocxlaVCHpKB_AAAAAA%3D%3D&vssid=jobs-detail-viewer",
      job_offer_expiration_datetime_utc: "2024-12-10T00:00:00.000Z",
      job_offer_expiration_timestamp: 1733788800,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 24,
        experience_mentioned: true,
        experience_preferred: true,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "2+ years' experience with Node and JavaScript",
          "Experience with AWS",
          "Knowledge of secure programming",
          "DevOps experience highly beneficial",
          "As long as you are well experienced in software development and can demonstrate a capacity to adjust to using these modern technologies, send in your application",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
      job_occupational_categories: [
        "15-1132.00: Software Developers, Applications",
      ],
      job_naics_code: null,
      job_naics_name: null,
    },
  ],
};

export { samplejobsData };
